matrix:
  include:
    - env: PHP_VERSION=5.6
    - env: PHP_VERSION=7.0
    - env: PHP_VERSION=7.1
    - env: PHP_VERSION=7.2

services:
  - docker

script:
  - make build TAG=$(printenv PHP_VERSION)
  - make run TAG=$(printenv PHP_VERSION)
  - make test TAG=$(printenv PHP_VERSION)
  - make stop

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="existenz" -p="$DOCKER_PASSWORD";
    docker push existenz/builder;
    fi

notifications:
  webhooks:
    urls:
      - https://$HOOKR_AUTH@hookr.enrise.com/webhooks-proxy/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
